name: Build and Push Custom n8n Docker Image to Docker Hub

on:
  push:
    branches:
      - main # mainブランチにプッシュされた時にこのワークフローを実行
  workflow_dispatch: # GitHubのActionsタブから手動で実行できるようにする（テストに便利）

jobs:
  build:
    runs-on: ubuntu-latest # GitHub Actionsの実行環境

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # リポジトリのコードをチェックアウト

      # --- ここから N8Nソースコードのビルドステップ ---
      - name: Set up Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest # ここを '8' から 'latest' に変更します
          run_install: false
          dest: ~/setup-pnpm


      - name: Cache pnpm modules
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store # pnpmのグローバルストアのパス
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Debug pnpm PATH # ★ 修正: ls コマンドの後に || true を追加
        run: |
          echo "Current PATH: $PATH"
          echo "Attempting to find pnpm with 'which pnpm':"
          which pnpm || echo "  'which pnpm' did not find pnpm"
          echo "Attempting to run 'pnpm -v' directly:"
          pnpm -v || echo "  'pnpm -v' command failed."
          echo "pnpm debug checks completed."


      - name: Install n8n dependencies
        run: pnpm install

      - name: Build n8n source code
        run: pnpm build

      - name: Move compiled artifacts to expected location
        run: |
          if [ -d "packages/main/compiled" ]; then
            echo "Moving compiled artifacts from packages/main/compiled to ./compiled"
            mv packages/main/compiled ./compiled
          else
            echo "Warning: packages/main/compiled not found. Assuming compiled artifacts are already in ./compiled or not needed by this Dockerfile."
          fi

      # --- N8Nソースコードのビルドステップ終了 ---

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: . # ここをリポジトリのルートに戻します
          file: ./docker/images/n8n/Dockerfile # Dockerfileの正確なパスを明示的に指定します
          push: true
          tags: yasu627177/n8n-custom:latest # ここが重要です
          cache-from: type=gha
          cache-to: type=gha,mode=max
          load: false
          no-cache: false
          pull: false
          github-token: ${{ secrets.GITHUB_TOKEN }}
